function nb_new = Refine(S0,delta)
% COUNTREFINE  counts the number of points that would be generated by the same call to Refine
%  
%   Synopsis: nb_new = CountRefine(S0,delta)
% 

     
  n = numel(S0.dim);
  
  if (isscalar(delta))
    delta = delta*ones(numel(S0.dim),1);
    
  elseif (size(delta,1)==1)
    delta=delta';
  end
  
  if (numel(delta)>numel(S0.dim))
    delta = delta(S0.dim);
  end;
  
  S.dim = S0.dim;
  S.pts =[];
  S.epsi = [];

  nb_new = 0;
  
  for i = 1:size(S0.pts,2)  
    deltai=delta;
  
    if (sum(abs(deltai-floor(deltai))));
      deltai(deltai>2*S0.epsi(:,i))=2*S0.epsi(deltai>2*S0.epsi(:,i));
      deltai = ceil(2*S0.epsi(:,i)./deltai);
    end
  
    nb_new = nb_new+prod(deltai);
    
  end


  