function solver_opt = setup_basic(this)
%  setup_basic basic solver: works with corners + quasi-random sampling   
% 

this.solver= 'basic';
dim_pb = numel(this.params);
solver_opt = struct( ...
    'use_param_set_as_init',false,...
    'start_at_trial', 0, ...
    'quasi_rand_seed', 0, ...
    'nb_max_corners', min(2^dim_pb, 10*dim_pb),...    
    'nb_new_trials',  min(2^dim_pb, 10*dim_pb)+10*numel(this.params) ...
    );

this.solver_options = solver_opt;
end
