function solver_opt = setup_global_nelder_mead(this)
this.solver= 'global_nelder_mead';
solver_opt = struct( ...
    'start_at_trial', 0, ...
    'nb_new_trials',  2^(numel(this.params))+10*numel(this.params), ...
    'nb_local_iter',  20, ...
    'local_optim_options', optimset() ...
    );
this.solver_options = solver_opt;
end
