addpath ../../DemoAFC/

listAFC = {'DemoAFC_1_Interface',...
           'DemoAFC_2_Simulation',...
           'DemoAFC_3_Sets',... 
           'DemoAFC_4_Specifications',...
           'DemoAFC_5_1_Falsification',...
           'DemoAFC_5_2_ParamSynth',...
           'DemoAFC_5_3_MaxSat',...
           'DemoAFC_5_4_ReqMining',...
           'DemoAFC_6_Analysis',...
           };

TestsAFC  = struct;

for nf = 1:numel(listAFC)
   TestsAFC.(listAFC{nf}) = DocRun(listAFC{nf}); 
end
       