InitBreach

Tests  = struct;

% Tutorial automatic transmission example
Tests.Autotrans_tutorial = DocRun('BrDemo.Autotrans_tutorial');

% Abstract Fuel Control model
listAFC = {...
    'AFC_1_Interface',...
    'AFC_2_Simulation',...
    'AFC_3_Sets',...
    'AFC_4_Specifications',...
    'AFC_5_1_Falsification',...
    'AFC_5_2_ParamSynth',...
    'AFC_5_3_MaxSat',...
    'AFC_5_4_ReqMining',...
    'AFC_6_Analysis',...
    };

% AFC Online

listAFC = [listAFC 'AFC_Online_Monitoring'];

for nf = 1:numel(listAFC)
    Tests.(listAFC{nf}) = DocRun(['BrDemo.' listAFC{nf}]);
end
